version: '3.8'

services:
  # Database Services
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root@1234
      MYSQL_DATABASE: order-service
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - productordering

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - productordering

  # Message Queue
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
      - "29092:29092"
    networks:
      - productordering

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - productordering

  # Microservices
  discovery-server:
    image: productordering/discovery-server:latest
    ports:
      - "8761:8761"
    networks:
      - productordering
    environment:
      - EUREKA_USERNAME=eureka
      - EUREKA_PASSWORD=password

  product-service:
    image: productordering/product-service:latest
    depends_on:
      - mongodb
      - discovery-server
    environment:
      - spring.data.mongodb.uri=mongodb://mongodb:27017/product-service
      - eureka.client.serviceUrl.defaultZone=http://eureka:password@discovery-server:8761/eureka
    networks:
      - productordering

  inventory-service:
    image: productordering/inventory-service:latest
    depends_on:
      - mysql
      - discovery-server
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/inventory-service?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root@1234
      - eureka.client.serviceUrl.defaultZone=http://eureka:password@discovery-server:8761/eureka
    networks:
      - productordering

  order-service:
    image: productordering/order-service:latest
    depends_on:
      - mysql
      - discovery-server
      - kafka
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/order-service?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root@1234
      - spring.kafka.bootstrap-servers=kafka:9092
      - eureka.client.serviceUrl.defaultZone=http://eureka:password@discovery-server:8761/eureka
    ports:
      - "8081:8081"
    networks:
      - productordering

  notification-service:
    image: productordering/notification-service:latest
    depends_on:
      - discovery-server
      - kafka
    environment:
      - spring.kafka.bootstrap-servers=kafka:9092
      - eureka.client.serviceUrl.defaultZone=http://eureka:password@discovery-server:8761/eureka
    networks:
      - productordering

  api-gateway:
    image: productordering/api-gateway:latest
    depends_on:
      - discovery-server
    ports:
      - "8080:8080"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:password@discovery-server:8761/eureka
    networks:
      - productordering

volumes:
  mysql_data:
  mongodb_data:

networks:
  productordering:
    driver: bridge
